import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import { useSession } from "next-auth/react";
export default function NavBar() {
  const { data: session } = useSession();
  let items = ["Home", "Create Posts", "About", "Login/Logout"];
  if (session) {
    items[3] = `${session.user.name}` 
  }
  const links = ["/", "createPost", "about", "auth"];
  return (
    <ul className=" flex justify-center text-2xl font-bold font-mono text-black bg-gradient-to-t from-blue-200 to to-blue-500">
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center gap-10">
        <Image src={"/slime.gif"} alt="logo" width={80} height={40} />
        {items.map((i, index) => (
          <li key={i}>
            <Link href={links[index]}>{i}</Link>
          </li>
        ))}
      </div>
    </ul>
  );
}
