/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import styles from "../styles/Home.module.css";
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
export default function Home({ data }) {
  const getAuthor = async (props) => {
    const response = await fetch("/api/post", {
      method: "GET",
      body: JSON.stringify(props),
    });
    let res = await response.json();
    if (!response.ok) {
      console.log(res.message);
    } else if (response.ok) {
      console.log(res.message);
      return res.email;
    }
  };
  return (
    <div className='bg-blue-200'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <ul className="grid mt-10 gap-10 font-mono text-black">
          {data.map((i) => (
            <div
              key={i.id}
              className="flex justify-center h-96"
            >
              <li className="border-4 border-blue-500 rounded-md grid justify-center grid-rows-5 bg-blue-400">
                <div className="flex justify-between row-span-1 m-4">
                  <div className="text-xl">- {i.title} -</div>
                  <div>{i.createdAt.substring(0, 10)}</div>
                </div>
                <div className="row-span-4">
                  <div className="grid grid-flow-col h-full">
                    <div className="w-72 bg-blue-200 p-4">
                      <img src={i.imageUrl} />
                    </div>
                    <div className="border-2 overflow-y-scroll w-96 p-2 break-words text-lg">
                      {i.content}
                    </div>
                  </div>
                </div>
              </li>
            </div>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const posts = await prisma.post.findMany();
  console.log(posts);
  return {
    props: {
      data: JSON.parse(JSON.stringify(posts)),
    }, // will be passed to the page component as props
  };
}
